const express = require("express");
const request = require("superagent");
const bodyParser = require("body-parser");

const mailsacAPIKey = ""; // Generated by mailsac. See https://mailsac.com/api-keys
const mailsacFromAddress = "web-application@mailsac.com";

const app = express();
const port = 3000;

// The static middleware will serve index.html at http://localhost:3000/
app.use(express.static("static"));
app.use(bodyParser.urlencoded({ extended: false }));

app.post("/create-user", async (req, res) => {
  const mailsacToEmailAddress = req.body.email;
  try {
    const confirmationMail = await request
      .post("https://mailsac.com/api/outgoing-messages")
      .set("Mailsac-Key", mailsacAPIKey)
      .send({
        to: mailsacToEmailAddress,
        from: mailsacFromAddress,
        subject: "Confirm your new example.com account",
        text: "Visit https://example.com to confirm you account",
        html:
          "<div><a href='https://example.com'>Confirm you account</a></div>",
      });
    if (confirmationMail.status != 200) {
      throw new Error(res.text);
    }
    res.redirect("/success.html");
  } catch (err) {
    res.status(err.status || 500);
    res.send("Failed to send email using Mailsac API: " + err);
  }
});

app.listen(port, () => {
  console.log(`Server started at http://localhost:${port}`);
});
